# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47fc11a589e98d98240e52a978fa7deedf634bccf0995e26699b313af3a2aaafc1194df9aa730e3db55f53c7d95ea1f6af041f78a5987f506011d968228a829a

test:
  secret_key_base: 594354aa05ddcb6f817aef3ff072fae5680fa94e1153c4541ff365021366bd20193e16ea06e55292cbe7a0a54d1ee1a4ab90cbe30669e47166f34f33da0b7859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
